sudo: required
dist: trusty
os: linux
language: generic
python:
  - "3.6"
script:
    - travis_retry sudo apt-get install libboost-all-dev libevent-dev libprotobuf-dev clang-3.8
    - test/test_all.py
