sudo: required
dist: trusty
os: linux
language: generic
python:
  - "3.6"
env:
  matrix:
    - TEST_SCRIPT="test/test_basic_style.py"
    - TEST_SCRIPT="test/test_clang_format.py"
    - TEST_SCRIPT="test/test_copyright_header.py"
    - TEST_SCRIPT="test/test_clang_static_analysis.py"
    - TEST_SCRIPT="test/test_checks.py"
    - TEST_SCRIPT="test/test_reports.py"
install:
    - travis_retry sudo apt-get install libboost-all-dev libevent-dev libprotobuf-dev clang-3.8
script:
    - $TEST_SCRIPT
